services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - ./app:/app
    container_name: app
    ports:
      - "3000:3000"
    entrypoint: su -c "npm install && tail -f /dev/null"
